# Generated by Django 5.2.12 on 2026-03-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('categories', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='masters/avatars/')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('wallet_balance', models.PositiveBigIntegerField(default=0, help_text='Stored in UZS minor units.')),
                ('free_contact_credits', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_profiles', to='categories.category')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('unlock_charge', 'Unlock Charge'), ('topup', 'Top Up'), ('refund', 'Refund')], db_index=True, max_length=20)),
                ('amount', models.PositiveBigIntegerField(help_text='Stored in UZS minor units.')),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.masterprofile')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='applications.jobapplication')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['category', 'is_verified'], name='wallet_mast_categor_1fb2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['city', 'district'], name='wallet_mast_city_1e42c5_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['master', 'created_at'], name='wallet_wall_master__9f1127_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type', 'created_at'], name='wallet_wall_type_63ca84_idx'),
        ),
    ]
