# Generated by Django 5.2.12 on 2026-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('contact_unlocked', 'Contact Unlocked')], db_index=True, default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_unlocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-applied_at',),
            },
        ),
    ]
